name: Deploy Static Website

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Step 1: Check out your repository code

      - name: Install dependencies (optional)
        # Use this step if your static site requires a build step (e.g., Node.js packages)
        # run: npm ci

      - name: Build static site (optional)
        # Use this step if you need to run a build command (e.g., 'npm run build')
        # This will create your static files in a directory like 'build' or 'dist'
        # run: npm run build
      - name: SFTP Deploy
        uses: wlix/sftp-deploy-action@v2
        with:
          host: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: ./michael-mkuegeler-blog/out/*
          remote_path: ${{ secrets.SFTP_TARGET }}
          # Optional: remove files on remote not in local
          delete_remote_files: true
